# Generated by Django 4.1.1 on 2022-10-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsnyc', '0002_alter_airq_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='airq',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airq',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
