# Generated by Django 4.1.1 on 2022-10-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsnyc', '0003_airq_latitude_airq_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airq',
            old_name='latitude',
            new_name='latitude_ne',
        ),
        migrations.RenameField(
            model_name='airq',
            old_name='longitude',
            new_name='latitude_sw',
        ),
        migrations.AddField(
            model_name='airq',
            name='longitude_ne',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airq',
            name='longitude_sw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
