# Generated by Django 4.1.1 on 2022-12-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsnyc', '0005_energy_temp_airq_aqi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energy',
            options={'managed': True},
        ),
    ]
