# Generated by Django 4.1.1 on 2022-12-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsnyc', '0007_alter_energy_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T',
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
        migrations.AlterModelOptions(
            name='airq',
            options={'managed': False},
        ),
    ]
